--个人网银临时表
create table PTMPDATA(  
  CIFSEQ      VARCHAR(32) not null,
  CIFNO       VARCHAR(64) not null,
  NEWCIF    VARCHAR(1),
  USERFLAG      VARCHAR(2),
  ACCOUNTFLAG VARCHAR(2),
  PAYEEFLAG   VARCHAR(2)
);
ALTER TABLE PTMPDATA ADD CONSTRAINT PK_PTMPDATA PRIMARY KEY(CIFSEQ);
ALTER TABLE PTMPDATA ADD CONSTRAINT PTMPDATA_U_CIFNO UNIQUE(CIFNO);
grant select on PTMPDATA to eip;
