delete from ECUSRAUTHMODMCH where mchannelid='PMBS' and userseq in(select userseq from ecusr u ,mtmpdata m where u.cifseq=m.cifseq);
commit;
delete from ECUSRAUTHMOD where userseq in(select userseq from ecusr where cifseq in(select cifseq from mtmpdata where newcif='Y'));
delete from ECUSRAUTHMOD where AUTHMOD = 'Q' and userseq in(select userseq from ecusr where cifseq in(select cifseq from mtmpdata));
commit;
delete from ECUSRLOGINTYPE where mchannelid='PMBS' and userseq in(select userseq from ecusr u ,mtmpdata m where u.cifseq=m.cifseq);
commit;
delete from ECUSRRULE where ruleid like 'PMBS%' and userseq in(select userseq from ecusr u ,mtmpdata m where u.cifseq=m.cifseq);
commit;
delete from ECUSRMCHACCT where mchannelid='PMBS' and userseq in(select userseq from ecusr u ,mtmpdata m where u.cifseq=m.cifseq);
commit;
delete from ECUSRMCH where mchannelid='PMBS' and userseq in(select userseq from ecusr u ,mtmpdata m where u.cifseq=m.cifseq);
commit;
delete from ECUSR where cifseq in(select cifseq from mtmpdata where newcif='Y');
commit;
delete from ECCIFTEL where cifseq in(select cifseq from MTMPDATA where newcif='Y');
commit;
delete from ECCIFRULE where cifseq in(select cifseq from MTMPDATA);
commit;
delete from ECPERS where cifseq in(select cifseq from MTMPDATA where newcif='Y');
commit;
delete from ECCIFPRODSET where mchannelid='PMBS' and cifseq in(select cifseq from MTMPDATA);
commit;
delete from ECCIFLIMIT where cifseq in(select cifseq from MTMPDATA);
commit;
delete from ECEXTCIFNO where cifseq in(select cifseq from MTMPDATA where newcif='Y');
commit;
delete from ECCIFID where cifseq in(select cifseq from MTMPDATA where newcif='Y');
commit;
delete from ECCIFMCH where mchannelid='PMBS' and cifseq in(select cifseq from MTMPDATA);
commit;
delete from ECCIFOUTTRANSFERSWITCH where mchannelid='PMBS' and cifseq in(select cifseq from MTMPDATA);
commit;
delete from ECCIF where cifseq in(select cifseq from MTMPDATA where newcif='Y');
commit;

update mtmpdata set userflag='NT' where userflag!='NT';
commit;
